### PR TITLE
JS now triggers 'promotion_tree_layout' when building the promotion tree...

### PR DESCRIPTION
**Pull request by honestabelink**
... layout

### CODE REVIEW

**Comment by Quit** [comment]
Thanks for the pull request! There's two things I'd like to see changed before I can pull it:
- In order to keep jelly uniform, I'd like to ask you to put the changes you make under the MIT license.
- In JavaScript, the comment blocks to indicate changes made by jelly are different (three lines).

For an example what it should look like, take a look at [Jelly.Console+'s override](/Quit/jelly_console/blob/master/console.js).

As for the code: Why didn't you use `$(top).trigger()` (or any other object)? I'm not too keen on JavaScript, but seeing as most of Stonehearth's systems use that way, I would opt to do use it too - unless there's a design decision behind that of course.

**Comment by honestabelink** [comment]
Let me know if there are any other problems. I like the solution you discussed on the discourse. If you don't have the free time now I'd be glad to give it a shot.

**Comment by Quit** [comment]
I don't want to sound too nitpicky, but I'd like a clean commit instead of just changing the stuff later (like a not-so-quite-stealthy-ninja):
- `$.Event` <-> `$(top).trigger`? Like I've said before, the "official" way would be the top-trigger one (see `stonehearth/ui/game/start_menu/start_menu.js` for lots of examples). Unless you've chosen the other way for any specific reason, I would rather use that one.
- Not sure about the license header to be honest. While I'm charmed that you give me credit for this, I don't think I deserve it. ;)

As for the general approach to the promotion screen, I don't know if/whether I can get to it in a reasonable time, so feel free to try it. You can always ask for feedback or specific things (but over at the Discourse).

**Comment by honestabelink** [comment]
I gave you partial credit for your advice to stick with Stonehearth's conventions to use 'top'. ;)

I also tell other people to follow their conventions too, but it was just something I overlooked.

Please pick away... :). So far your advice has been spot on.

I'll probably get around to the promotion screen sometime tomorrow or the day after. 

Thanks again RepeatPan

Edit
Think we're good to go...

**Comment by Quit** [comment]
Almost! Please rename the event to `jelly.PromotionTreeLayout` and we're good to go. I want to clearly distinguish what events are added by jelly and which ones are default/normal JavaScript.

Side note: This event, along with the whole function, will likely be gone once the data variant is implemented or at least modified. Because the whole thing will work completely different (multiple tabs/canvas instead of a singleton setup), the code for that section will likely be gone.

**Comment by honestabelink** [comment]
Once again good advice separating out events that are added.

I understood this is just temporary, I don't mind that it will be removed ;).

Thanks again RepeatPan, it's good to work with someone who follows a strict, but solid design philosophy. 

I am looking forward to continuing to work with you on Jelly. I am more than sure I'll learn a lot ;)

As a side note I'm putting implementing the new promotion tree on hold for a few days. Extra time I have now I'd like to focus on some community members on the discourse. Once everyone is good I'll return to Jelly.

Thanks again RepeatPan for your advice, and work so far on Jelly.
In the future I'll keep to the code in pull request's comments, and use the discourse to communicate my other thoughts ;)

**Comment by Quit** [comment]
And pulled. Thanks :smiley:.

To close this pull request for good: As for the new promotion thing, don't worry. It's a pretty big thing that I wouldn't want to tackle in a hurry either.

**Pull request merged**
